name = "ardstudio-api"
main = "src/index.js"
compatibility_date = "2026-07-29"

workers_dev = true

[observability]
enabled = true

[vars]
APP_NAME = "ARD Studio API"
API_VERSION = "2.0.0"


[ai]
binding = "AI"
